import type { Customer } from "../types/customer";

/**
 * Transform a raw `get_customer_info` API response into the app's Customer shape.
 * Shared by the customer search selection flow and the held-order resume flow so
 * both produce an identical, fully-populated Customer (including the required `id`).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function transformCustomerInfo(customer: any, fallbackCountry = ""): Customer {
  return {
    id: customer.name,
    type: customer.customer_type === "Company" ? "company" : (customer.is_walkin ? "walk-in" : "individual"),
    name: customer.customer_name || customer.name,
    customerName: customer.customer_name || customer.name,
    email: customer.contact_data?.email_id || customer.email_id || "",
    phone: customer.contact_data?.mobile_no || customer.contact_data?.phone || customer.mobile_no || "",
    address: {
      addressType: "Billing",
      street: customer.address_data?.address_line1 || "",
      buildingNumber: customer.address_data?.address_line2 || "",
      city: customer.address_data?.city || "",
      state: customer.address_data?.state || "",
      zipCode: customer.address_data?.pincode || "",
      country: customer.address_data?.country || fallbackCountry || "",
    },
    companyName: customer.company_name || (customer.customer_type === "Company" ? customer.customer_name : undefined),
    contactPerson: customer.contact_data ?
      `${customer.contact_data.first_name || ''} ${customer.contact_data.last_name || ''}`.trim() || customer.customer_name :
      customer.contact_person || customer.customer_name || "",
    taxId: customer.vat_number || customer.tax_id || "",
    isWalkin: customer.is_walkin || 0,
    industry: customer.industry || "",
    employeeCount: customer.employee_count || "",
    registrationScheme: customer.registration_scheme || "",
    registrationNumber: customer.registration_number || "",
    loyaltyPoints: customer.loyalty?.loyalty_points || customer.custom_loyalty_points || 0,
    totalSpent: customer.custom_total_spent || 0,
    totalOrders: customer.custom_total_orders || 0,
    preferredPaymentMethod: (customer.payment_method as "Cash" | "Bank Card" | "Bank Payment" | "Credit") || "Cash",
    tags: customer.custom_tags?.split(",").filter(Boolean) || [],
    status: (customer.custom_status as "active" | "inactive" | "vip") || "active",
    createdAt: customer.creation || new Date().toISOString(),
    lastVisit: customer.custom_last_visit || undefined,
    defaultCurrency: customer.currency || customer.price_list_currency || undefined,
    companyCurrency: customer.price_list_currency || undefined,
    customerGroup: customer.customer_group || "All Customer Groups",
    territory: customer.territory || "All Territories",
    emailId: customer.email_id || null,
    mobileNo: customer.mobile_no || null,
    customerType: customer.customer_type,
    customerPrimaryContact: customer.customer_primary_contact,
    customerPrimaryAddress: customer.customer_primary_address,
    contactData: customer.contact_data ? {
      firstName: customer.contact_data.first_name,
      lastName: customer.contact_data.last_name,
      emailId: customer.contact_data.email_id,
      phone: customer.contact_data.phone,
      mobileNo: customer.contact_data.mobile_no,
    } : null,
    addressData: customer.address_data ? {
      addressLine1: customer.address_data.address_line1,
      addressLine2: customer.address_data.address_line2,
      city: customer.address_data.city,
      state: customer.address_data.state,
      pincode: customer.address_data.pincode,
      country: customer.address_data.country,
    } : null,
    customerAddress: customer.customer_address,
    addressDisplay: customer.address_display || null,
    shippingAddressName: customer.shipping_address_name || null,
    shippingAddress: customer.shipping_address || null,
    taxCategory: customer.tax_category || null,
    contactPersonName: customer.contact_person || null,
    contactDisplay: customer.contact_display || null,
    contactEmail: customer.contact_email || null,
    contactMobile: customer.contact_mobile || null,
    contactPhone: customer.contact_phone || null,
    contactDesignation: customer.contact_designation || null,
    contactDepartment: customer.contact_department || null,
    taxWithholdingCategory: customer.tax_withholding_category || null,
    taxWithholdingGroup: customer.tax_withholding_group || null,
    language: customer.language || "en",
    priceListCurrency: customer.price_list_currency,
    sellingPriceList: customer.selling_price_list,
    paymentTermsTemplate: customer.payment_terms_template || null,
    currencyCode: customer.currency || null,
    salesTeam: customer.sales_team || [],
    vatNumber: customer.vat_number || "",
    paymentMethod: customer.payment_method || "Cash",
    loyalty: customer.loyalty || undefined,
    loyaltyProgram: customer.loyalty?.loyalty_program || null,
    loyaltyTier: customer.loyalty?.loyalty_program_tier || customer.loyalty?.customer_loyalty_program_tier || null,
    redeemableValue: customer.loyalty?.redeemable_value || 0,
  } as Customer;
}
